### ISSUE TITLE
Eclipse is throwing an exception when ToolProvider.getSystemJavaCompiler() returns null

### ISSUE THREAD

**Issue by samuelcardoso** [CruxFramework/crux-maven-plugin#24]
In order to solve this, we can start eclipse (using eclipse.ini) with a JDK instead of the default system JRE. But this is not the best solution, we should build a silent exception and avoid this.

This is the stacktrace:

Exception:org.eclipse.epp.internal.logging.aeri.ui.log.StandInStacktraceProvider$StandInException: Stand-In Stacktrace supplied by the Eclipse Error Reporting
     at org.eclipse.m2e.logback.appender.EclipseLogAppender.append(EclipseLogAppender.java:49)
     at org.eclipse.m2e.logback.appender.EclipseLogAppender.append(EclipseLogAppender.java:1)
     at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
     at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
     at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:280)
     at ch.qos.logback.classic.Logger.callAppenders(Logger.java:267)
     at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:449)
     at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:403)
     at ch.qos.logback.classic.Logger.error(Logger.java:550)
     at org.eclipse.m2e.core.internal.embedder.EclipseLogger.error(EclipseLogger.java:81)
     at org.apache.maven.monitor.logging.DefaultLog.error(DefaultLog.java:98)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
     at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
     at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
     at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
     at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
     at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
     at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
     at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
     at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
     at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
     at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
     at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
     at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
     at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
     at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
     at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
     at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
     at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
     at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
     at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

There's another stack trace probably related to this:

Exception:org.eclipse.swt.SWTException: Widget is disposed
     at org.eclipse.swt.SWT.error(SWT.java:4491)
     at org.eclipse.swt.SWT.error(SWT.java:4406)
     at org.eclipse.swt.SWT.error(SWT.java:4377)
     at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
     at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
     at org.eclipse.swt.widgets.Control.setRedraw(Control.java:3573)
     at org.eclipse.ui.forms.widgets.Section.reflow(Section.java:125)
     at org.eclipse.ui.forms.widgets.Section.internalSetExpanded(Section.java:115)
     at org.eclipse.ui.forms.widgets.ExpandableComposite.setExpanded(ExpandableComposite.java:882)
     at org.eclipse.m2e.editor.pom.OverviewPage$17$1.process(OverviewPage.java:1150)
     at org.eclipse.m2e.core.ui.internal.editing.PomEdits.performOnDOMDocument(PomEdits.java:510)
     at org.eclipse.m2e.editor.pom.OverviewPage$17.run(OverviewPage.java:1129)
     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
     at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
     at java.lang.reflect.Method.invoke(null:-1)
     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
     at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
     at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by thiagobustamante** [comment]
This is the expected behavior. You need to use a JDK to run crux-maven-plugin
